// Code generated by ogen, DO NOT EDIT.

package api

type HealthCheckOK struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthCheckOK) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthCheckOK) SetStatus(val string) {
	s.Status = val
}
